import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { memo } from 'react';

import Providers from './providers';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}

export default memo(RootLayout);
